//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
[System.Xml.Serialization.XmlRootAttribute("MTConnectAssets", Namespace="urn:mtconnect.org:MTConnectAssets:1.3", IsNullable=false)]
public partial class MTConnectAssetsType {
    
    private HeaderType headerField;
    
    private AssetType[] assetsField;
    
    /// <remarks/>
    public HeaderType Header {
        get {
            return this.headerField;
        }
        set {
            this.headerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Asset", IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("CuttingTool", typeof(CuttingToolType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("CuttingToolArchetype", typeof(CuttingToolArchetypeType), IsNullable=false)]
    public AssetType[] Assets {
        get {
            return this.assetsField;
        }
        set {
            this.assetsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
public partial class CuttingToolLifeCycleArchetypeType {
    
    private ReconditionCountType reconditionCountField;
    
    private LifeType[] toolLifeField;
    
    private string programToolGroupField;
    
    private string programToolNumberField;
    
    private ProcessSpindleSpeedType processSpindleSpeedField;
    
    private ProcessFeedRateType processFeedRateField;
    
    private string connectionCodeMachineSideField;
    
    private MeasurementType[] measurementsField;
    
    private CuttingItemsType cuttingItemsField;
    
    /// <remarks/>
    public ReconditionCountType ReconditionCount {
        get {
            return this.reconditionCountField;
        }
        set {
            this.reconditionCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ToolLife")]
    public LifeType[] ToolLife {
        get {
            return this.toolLifeField;
        }
        set {
            this.toolLifeField = value;
        }
    }
    
    /// <remarks/>
    public string ProgramToolGroup {
        get {
            return this.programToolGroupField;
        }
        set {
            this.programToolGroupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string ProgramToolNumber {
        get {
            return this.programToolNumberField;
        }
        set {
            this.programToolNumberField = value;
        }
    }
    
    /// <remarks/>
    public ProcessSpindleSpeedType ProcessSpindleSpeed {
        get {
            return this.processSpindleSpeedField;
        }
        set {
            this.processSpindleSpeedField = value;
        }
    }
    
    /// <remarks/>
    public ProcessFeedRateType ProcessFeedRate {
        get {
            return this.processFeedRateField;
        }
        set {
            this.processFeedRateField = value;
        }
    }
    
    /// <remarks/>
    public string ConnectionCodeMachineSide {
        get {
            return this.connectionCodeMachineSideField;
        }
        set {
            this.connectionCodeMachineSideField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("AssemblyMeasurement", typeof(AssemblyMeasurementType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("BodyDiameterMax", typeof(BodyDiameterMaxType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("BodyLengthMax", typeof(BodyLengthMaxType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("CommonMeasurement", typeof(CommonMeasurementType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("CuttingDiameterMax", typeof(CuttingDiameterMaxType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("DepthOfCutMax", typeof(DepthOfCutMaxType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("FlangeDiameterMax", typeof(FlangeDiameterMaxType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("FunctionalLength", typeof(FunctionalLengthType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("OverallToolLength", typeof(OverallToolLengthType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ProtrudingLength", typeof(ProtrudingLengthType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ShankDiameter", typeof(ShankDiameterType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ShankHeight", typeof(ShankHeightType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ShankLength", typeof(ShankLengthType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("UsableLengthMax", typeof(UsableLengthMaxType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Weight", typeof(WeightType), IsNullable=false)]
    public MeasurementType[] Measurements {
        get {
            return this.measurementsField;
        }
        set {
            this.measurementsField = value;
        }
    }
    
    /// <remarks/>
    public CuttingItemsType CuttingItems {
        get {
            return this.cuttingItemsField;
        }
        set {
            this.cuttingItemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
public partial class ReconditionCountType {
    
    private string maximumCountField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string maximumCount {
        get {
            return this.maximumCountField;
        }
        set {
            this.maximumCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
public partial class LifeType {
    
    private ToolLifeType typeField;
    
    private ToolLifeDirectionType countDirectionField;
    
    private float warningField;
    
    private bool warningFieldSpecified;
    
    private float limitField;
    
    private float initialField;
    
    private float valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ToolLifeType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ToolLifeDirectionType countDirection {
        get {
            return this.countDirectionField;
        }
        set {
            this.countDirectionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float warning {
        get {
            return this.warningField;
        }
        set {
            this.warningField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool warningSpecified {
        get {
            return this.warningFieldSpecified;
        }
        set {
            this.warningFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float limit {
        get {
            return this.limitField;
        }
        set {
            this.limitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float initial {
        get {
            return this.initialField;
        }
        set {
            this.initialField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public float Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
public enum ToolLifeType {
    
    /// <remarks/>
    MINUTES,
    
    /// <remarks/>
    PART_COUNT,
    
    /// <remarks/>
    WEAR,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
public enum ToolLifeDirectionType {
    
    /// <remarks/>
    UP,
    
    /// <remarks/>
    DOWN,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
public partial class ProcessSpindleSpeedType {
    
    private float maximumField;
    
    private bool maximumFieldSpecified;
    
    private float minimumField;
    
    private bool minimumFieldSpecified;
    
    private float nominalField;
    
    private bool nominalFieldSpecified;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float maximum {
        get {
            return this.maximumField;
        }
        set {
            this.maximumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maximumSpecified {
        get {
            return this.maximumFieldSpecified;
        }
        set {
            this.maximumFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float minimum {
        get {
            return this.minimumField;
        }
        set {
            this.minimumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool minimumSpecified {
        get {
            return this.minimumFieldSpecified;
        }
        set {
            this.minimumFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float nominal {
        get {
            return this.nominalField;
        }
        set {
            this.nominalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool nominalSpecified {
        get {
            return this.nominalFieldSpecified;
        }
        set {
            this.nominalFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
public partial class ProcessFeedRateType {
    
    private float maximumField;
    
    private bool maximumFieldSpecified;
    
    private float minimumField;
    
    private bool minimumFieldSpecified;
    
    private float nominalField;
    
    private bool nominalFieldSpecified;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float maximum {
        get {
            return this.maximumField;
        }
        set {
            this.maximumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maximumSpecified {
        get {
            return this.maximumFieldSpecified;
        }
        set {
            this.maximumFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float minimum {
        get {
            return this.minimumField;
        }
        set {
            this.minimumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool minimumSpecified {
        get {
            return this.minimumFieldSpecified;
        }
        set {
            this.minimumFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float nominal {
        get {
            return this.nominalField;
        }
        set {
            this.nominalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool nominalSpecified {
        get {
            return this.nominalFieldSpecified;
        }
        set {
            this.nominalFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(UsableLengthMaxType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ShankLengthType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ShankHeightType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ShankDiameterType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(OverallToolLengthType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DepthOfCutMaxType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(FlangeDiameterMaxType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CuttingDiameterMaxType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BodyLengthMaxType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BodyDiameterMaxType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
public abstract partial class AssemblyMeasurementType : MeasurementType {
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CuttingItemMeasurementType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(WiperEdgeLengthType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ToolLeadAngleType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ToolCuttingEdgeAngleType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(StepIncludedAngleType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(StepDiameterLengthType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PointAngleType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(IncribedCircleDiameterType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(InclinationAngleType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(FunctionalWidthType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(FlangeDiameterType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CuttingReferencePointType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CuttingHeightType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CuttingEdgeLengthType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CornerRadiusType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CuttingDiameterType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AssemblyMeasurementType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(UsableLengthMaxType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ShankLengthType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ShankHeightType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ShankDiameterType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(OverallToolLengthType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DepthOfCutMaxType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(FlangeDiameterMaxType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CuttingDiameterMaxType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BodyLengthMaxType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BodyDiameterMaxType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CommonMeasurementType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(FunctionalLengthType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(WeightType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ProtrudingLengthType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
public abstract partial class MeasurementType {
    
    private string significantDigitsField;
    
    private string unitsField;
    
    private string nativeUnitsField;
    
    private string codeField;
    
    private float maximumField;
    
    private bool maximumFieldSpecified;
    
    private float minimumField;
    
    private bool minimumFieldSpecified;
    
    private float nominalField;
    
    private bool nominalFieldSpecified;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string significantDigits {
        get {
            return this.significantDigitsField;
        }
        set {
            this.significantDigitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nativeUnits {
        get {
            return this.nativeUnitsField;
        }
        set {
            this.nativeUnitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float maximum {
        get {
            return this.maximumField;
        }
        set {
            this.maximumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maximumSpecified {
        get {
            return this.maximumFieldSpecified;
        }
        set {
            this.maximumFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float minimum {
        get {
            return this.minimumField;
        }
        set {
            this.minimumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool minimumSpecified {
        get {
            return this.minimumFieldSpecified;
        }
        set {
            this.minimumFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float nominal {
        get {
            return this.nominalField;
        }
        set {
            this.nominalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool nominalSpecified {
        get {
            return this.nominalFieldSpecified;
        }
        set {
            this.nominalFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(WiperEdgeLengthType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ToolLeadAngleType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ToolCuttingEdgeAngleType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(StepIncludedAngleType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(StepDiameterLengthType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PointAngleType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(IncribedCircleDiameterType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(InclinationAngleType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(FunctionalWidthType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(FlangeDiameterType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CuttingReferencePointType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CuttingHeightType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CuttingEdgeLengthType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CornerRadiusType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CuttingDiameterType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
public abstract partial class CuttingItemMeasurementType : MeasurementType {
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(FunctionalLengthType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(WeightType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ProtrudingLengthType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
public abstract partial class CommonMeasurementType : MeasurementType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
[System.Xml.Serialization.XmlRootAttribute("BodyDiameterMax", Namespace="urn:mtconnect.org:MTConnectAssets:1.3", IsNullable=false)]
public partial class BodyDiameterMaxType : AssemblyMeasurementType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
[System.Xml.Serialization.XmlRootAttribute("BodyLengthMax", Namespace="urn:mtconnect.org:MTConnectAssets:1.3", IsNullable=false)]
public partial class BodyLengthMaxType : AssemblyMeasurementType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
[System.Xml.Serialization.XmlRootAttribute("CuttingDiameterMax", Namespace="urn:mtconnect.org:MTConnectAssets:1.3", IsNullable=false)]
public partial class CuttingDiameterMaxType : AssemblyMeasurementType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
[System.Xml.Serialization.XmlRootAttribute("DepthOfCutMax", Namespace="urn:mtconnect.org:MTConnectAssets:1.3", IsNullable=false)]
public partial class DepthOfCutMaxType : AssemblyMeasurementType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
[System.Xml.Serialization.XmlRootAttribute("FlangeDiameterMax", Namespace="urn:mtconnect.org:MTConnectAssets:1.3", IsNullable=false)]
public partial class FlangeDiameterMaxType : AssemblyMeasurementType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
[System.Xml.Serialization.XmlRootAttribute("FunctionalLength", Namespace="urn:mtconnect.org:MTConnectAssets:1.3", IsNullable=false)]
public partial class FunctionalLengthType : CommonMeasurementType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
[System.Xml.Serialization.XmlRootAttribute("OverallToolLength", Namespace="urn:mtconnect.org:MTConnectAssets:1.3", IsNullable=false)]
public partial class OverallToolLengthType : AssemblyMeasurementType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
[System.Xml.Serialization.XmlRootAttribute("ProtrudingLength", Namespace="urn:mtconnect.org:MTConnectAssets:1.3", IsNullable=false)]
public partial class ProtrudingLengthType : CommonMeasurementType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
[System.Xml.Serialization.XmlRootAttribute("ShankDiameter", Namespace="urn:mtconnect.org:MTConnectAssets:1.3", IsNullable=false)]
public partial class ShankDiameterType : AssemblyMeasurementType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
[System.Xml.Serialization.XmlRootAttribute("ShankHeight", Namespace="urn:mtconnect.org:MTConnectAssets:1.3", IsNullable=false)]
public partial class ShankHeightType : AssemblyMeasurementType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
[System.Xml.Serialization.XmlRootAttribute("ShankLength", Namespace="urn:mtconnect.org:MTConnectAssets:1.3", IsNullable=false)]
public partial class ShankLengthType : AssemblyMeasurementType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
[System.Xml.Serialization.XmlRootAttribute("UsableLengthMax", Namespace="urn:mtconnect.org:MTConnectAssets:1.3", IsNullable=false)]
public partial class UsableLengthMaxType : AssemblyMeasurementType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
[System.Xml.Serialization.XmlRootAttribute("Weight", Namespace="urn:mtconnect.org:MTConnectAssets:1.3", IsNullable=false)]
public partial class WeightType : CommonMeasurementType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
public partial class CuttingItemsType {
    
    private CuttingItemType[] cuttingItemField;
    
    private string countField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CuttingItem")]
    public CuttingItemType[] CuttingItem {
        get {
            return this.cuttingItemField;
        }
        set {
            this.cuttingItemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
public partial class CuttingItemType {
    
    private AssetDescriptionType descriptionField;
    
    private string locusField;
    
    private LifeType[] itemLifeField;
    
    private MeasurementType[] measurementsField;
    
    private string indicesField;
    
    private string itemIdField;
    
    private string gradeField;
    
    private string manufacturersField;
    
    /// <remarks/>
    public AssetDescriptionType Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string Locus {
        get {
            return this.locusField;
        }
        set {
            this.locusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemLife")]
    public LifeType[] ItemLife {
        get {
            return this.itemLifeField;
        }
        set {
            this.itemLifeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("CommonMeasurement", typeof(CommonMeasurementType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("CornerRadius", typeof(CornerRadiusType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("CuttingDiameter", typeof(CuttingDiameterType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("CuttingEdgeLength", typeof(CuttingEdgeLengthType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("CuttingHeight", typeof(CuttingHeightType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("CuttingItemMeasurement", typeof(CuttingItemMeasurementType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("CuttingReferencePoint", typeof(CuttingReferencePointType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("FlangeDiameter", typeof(FlangeDiameterType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("FunctionalLength", typeof(FunctionalLengthType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("FunctionalWidth", typeof(FunctionalWidthType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("InclinationAngle", typeof(InclinationAngleType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("IncribedCircleDiameter", typeof(IncribedCircleDiameterType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("PointAngle", typeof(PointAngleType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ProtrudingLength", typeof(ProtrudingLengthType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("StepDiameterLength", typeof(StepDiameterLengthType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("StepIncludedAngle", typeof(StepIncludedAngleType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ToolCuttingEdgeAngle", typeof(ToolCuttingEdgeAngleType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ToolLeadAngle", typeof(ToolLeadAngleType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Weight", typeof(WeightType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("WiperEdgeLength", typeof(WiperEdgeLengthType), IsNullable=false)]
    public MeasurementType[] Measurements {
        get {
            return this.measurementsField;
        }
        set {
            this.measurementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string indices {
        get {
            return this.indicesField;
        }
        set {
            this.indicesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string itemId {
        get {
            return this.itemIdField;
        }
        set {
            this.itemIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string grade {
        get {
            return this.gradeField;
        }
        set {
            this.gradeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string manufacturers {
        get {
            return this.manufacturersField;
        }
        set {
            this.manufacturersField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
public partial class AssetDescriptionType {
    
    private System.Xml.XmlNode[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlNode[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
[System.Xml.Serialization.XmlRootAttribute("CornerRadius", Namespace="urn:mtconnect.org:MTConnectAssets:1.3", IsNullable=false)]
public partial class CornerRadiusType : CuttingItemMeasurementType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
[System.Xml.Serialization.XmlRootAttribute("CuttingDiameter", Namespace="urn:mtconnect.org:MTConnectAssets:1.3", IsNullable=false)]
public partial class CuttingDiameterType : CuttingItemMeasurementType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
[System.Xml.Serialization.XmlRootAttribute("CuttingEdgeLength", Namespace="urn:mtconnect.org:MTConnectAssets:1.3", IsNullable=false)]
public partial class CuttingEdgeLengthType : CuttingItemMeasurementType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
[System.Xml.Serialization.XmlRootAttribute("CuttingHeight", Namespace="urn:mtconnect.org:MTConnectAssets:1.3", IsNullable=false)]
public partial class CuttingHeightType : CuttingItemMeasurementType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
[System.Xml.Serialization.XmlRootAttribute("CuttingReferencePoint", Namespace="urn:mtconnect.org:MTConnectAssets:1.3", IsNullable=false)]
public partial class CuttingReferencePointType : CuttingItemMeasurementType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
[System.Xml.Serialization.XmlRootAttribute("FlangeDiameter", Namespace="urn:mtconnect.org:MTConnectAssets:1.3", IsNullable=false)]
public partial class FlangeDiameterType : CuttingItemMeasurementType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
[System.Xml.Serialization.XmlRootAttribute("FunctionalWidth", Namespace="urn:mtconnect.org:MTConnectAssets:1.3", IsNullable=false)]
public partial class FunctionalWidthType : CuttingItemMeasurementType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
[System.Xml.Serialization.XmlRootAttribute("InclinationAngle", Namespace="urn:mtconnect.org:MTConnectAssets:1.3", IsNullable=false)]
public partial class InclinationAngleType : CuttingItemMeasurementType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
[System.Xml.Serialization.XmlRootAttribute("IncribedCircleDiameter", Namespace="urn:mtconnect.org:MTConnectAssets:1.3", IsNullable=false)]
public partial class IncribedCircleDiameterType : CuttingItemMeasurementType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
[System.Xml.Serialization.XmlRootAttribute("PointAngle", Namespace="urn:mtconnect.org:MTConnectAssets:1.3", IsNullable=false)]
public partial class PointAngleType : CuttingItemMeasurementType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
[System.Xml.Serialization.XmlRootAttribute("StepDiameterLength", Namespace="urn:mtconnect.org:MTConnectAssets:1.3", IsNullable=false)]
public partial class StepDiameterLengthType : CuttingItemMeasurementType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
[System.Xml.Serialization.XmlRootAttribute("StepIncludedAngle", Namespace="urn:mtconnect.org:MTConnectAssets:1.3", IsNullable=false)]
public partial class StepIncludedAngleType : CuttingItemMeasurementType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
[System.Xml.Serialization.XmlRootAttribute("ToolCuttingEdgeAngle", Namespace="urn:mtconnect.org:MTConnectAssets:1.3", IsNullable=false)]
public partial class ToolCuttingEdgeAngleType : CuttingItemMeasurementType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
[System.Xml.Serialization.XmlRootAttribute("ToolLeadAngle", Namespace="urn:mtconnect.org:MTConnectAssets:1.3", IsNullable=false)]
public partial class ToolLeadAngleType : CuttingItemMeasurementType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
[System.Xml.Serialization.XmlRootAttribute("WiperEdgeLength", Namespace="urn:mtconnect.org:MTConnectAssets:1.3", IsNullable=false)]
public partial class WiperEdgeLengthType : CuttingItemMeasurementType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
public partial class LocationType {
    
    private LocationsType typeField;
    
    private string negativeOverlapField;
    
    private string positiveOverlapField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public LocationsType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string negativeOverlap {
        get {
            return this.negativeOverlapField;
        }
        set {
            this.negativeOverlapField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string positiveOverlap {
        get {
            return this.positiveOverlapField;
        }
        set {
            this.positiveOverlapField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
public enum LocationsType {
    
    /// <remarks/>
    POT,
    
    /// <remarks/>
    STATION,
    
    /// <remarks/>
    CRIB,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
public partial class CuttingToolLifeCycleType {
    
    private CutterStatusValueType[] cutterStatusField;
    
    private ReconditionCountType reconditionCountField;
    
    private LifeType[] toolLifeField;
    
    private string programToolGroupField;
    
    private string programToolNumberField;
    
    private LocationType locationField;
    
    private ProcessSpindleSpeedType processSpindleSpeedField;
    
    private ProcessFeedRateType processFeedRateField;
    
    private string connectionCodeMachineSideField;
    
    private MeasurementType[] measurementsField;
    
    private CuttingItemsType cuttingItemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Status", IsNullable=false)]
    public CutterStatusValueType[] CutterStatus {
        get {
            return this.cutterStatusField;
        }
        set {
            this.cutterStatusField = value;
        }
    }
    
    /// <remarks/>
    public ReconditionCountType ReconditionCount {
        get {
            return this.reconditionCountField;
        }
        set {
            this.reconditionCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ToolLife")]
    public LifeType[] ToolLife {
        get {
            return this.toolLifeField;
        }
        set {
            this.toolLifeField = value;
        }
    }
    
    /// <remarks/>
    public string ProgramToolGroup {
        get {
            return this.programToolGroupField;
        }
        set {
            this.programToolGroupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string ProgramToolNumber {
        get {
            return this.programToolNumberField;
        }
        set {
            this.programToolNumberField = value;
        }
    }
    
    /// <remarks/>
    public LocationType Location {
        get {
            return this.locationField;
        }
        set {
            this.locationField = value;
        }
    }
    
    /// <remarks/>
    public ProcessSpindleSpeedType ProcessSpindleSpeed {
        get {
            return this.processSpindleSpeedField;
        }
        set {
            this.processSpindleSpeedField = value;
        }
    }
    
    /// <remarks/>
    public ProcessFeedRateType ProcessFeedRate {
        get {
            return this.processFeedRateField;
        }
        set {
            this.processFeedRateField = value;
        }
    }
    
    /// <remarks/>
    public string ConnectionCodeMachineSide {
        get {
            return this.connectionCodeMachineSideField;
        }
        set {
            this.connectionCodeMachineSideField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("AssemblyMeasurement", typeof(AssemblyMeasurementType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("BodyDiameterMax", typeof(BodyDiameterMaxType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("BodyLengthMax", typeof(BodyLengthMaxType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("CommonMeasurement", typeof(CommonMeasurementType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("CuttingDiameterMax", typeof(CuttingDiameterMaxType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("DepthOfCutMax", typeof(DepthOfCutMaxType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("FlangeDiameterMax", typeof(FlangeDiameterMaxType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("FunctionalLength", typeof(FunctionalLengthType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("OverallToolLength", typeof(OverallToolLengthType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ProtrudingLength", typeof(ProtrudingLengthType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ShankDiameter", typeof(ShankDiameterType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ShankHeight", typeof(ShankHeightType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ShankLength", typeof(ShankLengthType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("UsableLengthMax", typeof(UsableLengthMaxType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Weight", typeof(WeightType), IsNullable=false)]
    public MeasurementType[] Measurements {
        get {
            return this.measurementsField;
        }
        set {
            this.measurementsField = value;
        }
    }
    
    /// <remarks/>
    public CuttingItemsType CuttingItems {
        get {
            return this.cuttingItemsField;
        }
        set {
            this.cuttingItemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
public enum CutterStatusValueType {
    
    /// <remarks/>
    NEW,
    
    /// <remarks/>
    AVAILABLE,
    
    /// <remarks/>
    UNAVAILABLE,
    
    /// <remarks/>
    ALLOCATED,
    
    /// <remarks/>
    UNALLOCATED,
    
    /// <remarks/>
    MEASURED,
    
    /// <remarks/>
    NOT_REGISTERED,
    
    /// <remarks/>
    RECONDITIONED,
    
    /// <remarks/>
    USED,
    
    /// <remarks/>
    EXPIRED,
    
    /// <remarks/>
    TAGGED_OUT,
    
    /// <remarks/>
    BROKEN,
    
    /// <remarks/>
    UNKNOWN,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
public partial class CuttingToolDefinitionType {
    
    private System.Xml.XmlNode[] anyField;
    
    private DefinitionFormatType formatField;
    
    private bool formatFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlNode[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public DefinitionFormatType format {
        get {
            return this.formatField;
        }
        set {
            this.formatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool formatSpecified {
        get {
            return this.formatFieldSpecified;
        }
        set {
            this.formatFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
public enum DefinitionFormatType {
    
    /// <remarks/>
    EXPRESS,
    
    /// <remarks/>
    XML,
    
    /// <remarks/>
    TEXT,
    
    /// <remarks/>
    UNDEFINED,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
public partial class CuttingToolArchetypeReferenceType {
    
    private string sourceField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CuttingToolArchetypeType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CuttingToolType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
public abstract partial class AssetType {
    
    private string assetIdField;
    
    private System.DateTime timestampField;
    
    private string deviceUuidField;
    
    private bool removedField;
    
    private bool removedFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string assetId {
        get {
            return this.assetIdField;
        }
        set {
            this.assetIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime timestamp {
        get {
            return this.timestampField;
        }
        set {
            this.timestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string deviceUuid {
        get {
            return this.deviceUuidField;
        }
        set {
            this.deviceUuidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool removed {
        get {
            return this.removedField;
        }
        set {
            this.removedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool removedSpecified {
        get {
            return this.removedFieldSpecified;
        }
        set {
            this.removedFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
[System.Xml.Serialization.XmlRootAttribute("CuttingTool", Namespace="urn:mtconnect.org:MTConnectAssets:1.3", IsNullable=false)]
public partial class CuttingToolType : AssetType {
    
    private AssetDescriptionType descriptionField;
    
    private CuttingToolArchetypeReferenceType cuttingToolArchetypeReferenceField;
    
    private object[] itemsField;
    
    private string serialNumberField;
    
    private string manufacturersField;
    
    private string toolIdField;
    
    /// <remarks/>
    public AssetDescriptionType Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public CuttingToolArchetypeReferenceType CuttingToolArchetypeReference {
        get {
            return this.cuttingToolArchetypeReferenceField;
        }
        set {
            this.cuttingToolArchetypeReferenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CuttingToolDefinition", typeof(CuttingToolDefinitionType))]
    [System.Xml.Serialization.XmlElementAttribute("CuttingToolLifeCycle", typeof(CuttingToolLifeCycleType))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string serialNumber {
        get {
            return this.serialNumberField;
        }
        set {
            this.serialNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string manufacturers {
        get {
            return this.manufacturersField;
        }
        set {
            this.manufacturersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string toolId {
        get {
            return this.toolIdField;
        }
        set {
            this.toolIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectAssets:1.3")]
[System.Xml.Serialization.XmlRootAttribute("CuttingToolArchetype", Namespace="urn:mtconnect.org:MTConnectAssets:1.3", IsNullable=false)]
public partial class CuttingToolArchetypeType : AssetType {
    
    private AssetDescriptionType descriptionField;
    
    private object[] itemsField;
    
    private string toolIdField;
    
    /// <remarks/>
    public AssetDescriptionType Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CuttingToolDefinition", typeof(CuttingToolDefinitionType))]
    [System.Xml.Serialization.XmlElementAttribute("CuttingToolLifeCycle", typeof(CuttingToolLifeCycleArchetypeType))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string toolId {
        get {
            return this.toolIdField;
        }
        set {
            this.toolIdField = value;
        }
    }
}
