//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectDevices:1.3")]
[System.Xml.Serialization.XmlRootAttribute("MTConnectDevices", Namespace="urn:mtconnect.org:MTConnectDevices:1.3", IsNullable=false)]
public partial class MTConnectDevicesType {
    
    private HeaderType headerField;
    
    private DeviceType[] devicesField;
    
    /// <remarks/>
    public HeaderType Header {
        get {
            return this.headerField;
        }
        set {
            this.headerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Device", IsNullable=false)]
    public DeviceType[] Devices {
        get {
            return this.devicesField;
        }
        set {
            this.devicesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectDevices:1.3")]
public partial class AssetCountType {
    
    private string assetTypeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string assetType {
        get {
            return this.assetTypeField;
        }
        set {
            this.assetTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectDevices:1.3")]
public partial class ReferenceType {
    
    private string dataItemIdField;
    
    private string nameField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string dataItemId {
        get {
            return this.dataItemIdField;
        }
        set {
            this.dataItemIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectDevices:1.3")]
public partial class DataItemFilterType {
    
    private FilterType typeField;
    
    private float valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public FilterType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public float Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectDevices:1.3")]
public enum FilterType {
    
    /// <remarks/>
    MINIMUM_DELTA,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectDevices:1.3")]
public partial class DataItemValueElementType {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectDevices:1.3")]
public partial class DataItemConstraintsType {
    
    private object[] itemsField;
    
    private ItemsChoiceType[] itemsElementNameField;
    
    private DataItemFilterType filterField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Maximum", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Minimum", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Value", typeof(DataItemValueElementType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
    
    /// <remarks/>
    public DataItemFilterType Filter {
        get {
            return this.filterField;
        }
        set {
            this.filterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectDevices:1.3", IncludeInSchema=false)]
public enum ItemsChoiceType {
    
    /// <remarks/>
    Maximum,
    
    /// <remarks/>
    Minimum,
    
    /// <remarks/>
    Value,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectDevices:1.3")]
public partial class SourceType {
    
    private string componentIdField;
    
    private string dataItemIdField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string componentId {
        get {
            return this.componentIdField;
        }
        set {
            this.componentIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string dataItemId {
        get {
            return this.dataItemIdField;
        }
        set {
            this.dataItemIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectDevices:1.3")]
public partial class DataItemType {
    
    private SourceType sourceField;
    
    private DataItemConstraintsType constraintsField;
    
    private string nameField;
    
    private string idField;
    
    private string typeField;
    
    private string subTypeField;
    
    private string statisticField;
    
    private string unitsField;
    
    private string nativeUnitsField;
    
    private float nativeScaleField;
    
    private bool nativeScaleFieldSpecified;
    
    private CategoryType categoryField;
    
    private CoordinateSystemType coordinateSystemField;
    
    private bool coordinateSystemFieldSpecified;
    
    private float sampleRateField;
    
    private bool sampleRateFieldSpecified;
    
    private RepresentationType representationField;
    
    private string significantDigitsField;
    
    public DataItemType() {
        this.representationField = RepresentationType.VALUE;
    }
    
    /// <remarks/>
    public SourceType Source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    public DataItemConstraintsType Constraints {
        get {
            return this.constraintsField;
        }
        set {
            this.constraintsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string subType {
        get {
            return this.subTypeField;
        }
        set {
            this.subTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string statistic {
        get {
            return this.statisticField;
        }
        set {
            this.statisticField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nativeUnits {
        get {
            return this.nativeUnitsField;
        }
        set {
            this.nativeUnitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float nativeScale {
        get {
            return this.nativeScaleField;
        }
        set {
            this.nativeScaleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool nativeScaleSpecified {
        get {
            return this.nativeScaleFieldSpecified;
        }
        set {
            this.nativeScaleFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public CategoryType category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public CoordinateSystemType coordinateSystem {
        get {
            return this.coordinateSystemField;
        }
        set {
            this.coordinateSystemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool coordinateSystemSpecified {
        get {
            return this.coordinateSystemFieldSpecified;
        }
        set {
            this.coordinateSystemFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float sampleRate {
        get {
            return this.sampleRateField;
        }
        set {
            this.sampleRateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool sampleRateSpecified {
        get {
            return this.sampleRateFieldSpecified;
        }
        set {
            this.sampleRateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(RepresentationType.VALUE)]
    public RepresentationType representation {
        get {
            return this.representationField;
        }
        set {
            this.representationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string significantDigits {
        get {
            return this.significantDigitsField;
        }
        set {
            this.significantDigitsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectDevices:1.3")]
public enum CategoryType {
    
    /// <remarks/>
    EVENT,
    
    /// <remarks/>
    SAMPLE,
    
    /// <remarks/>
    CONDITION,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectDevices:1.3")]
public enum CoordinateSystemType {
    
    /// <remarks/>
    MACHINE,
    
    /// <remarks/>
    WORK,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectDevices:1.3")]
public enum RepresentationType {
    
    /// <remarks/>
    VALUE,
    
    /// <remarks/>
    TIME_SERIES,
    
    /// <remarks/>
    DISCRETE,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectDevices:1.3")]
public partial class ChannelType {
    
    private string descriptionField;
    
    private System.DateTime calibrationDateField;
    
    private bool calibrationDateFieldSpecified;
    
    private System.DateTime nextCalibrationDateField;
    
    private bool nextCalibrationDateFieldSpecified;
    
    private string calibrationInitialsField;
    
    private string numberField;
    
    private string nameField;
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime CalibrationDate {
        get {
            return this.calibrationDateField;
        }
        set {
            this.calibrationDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CalibrationDateSpecified {
        get {
            return this.calibrationDateFieldSpecified;
        }
        set {
            this.calibrationDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime NextCalibrationDate {
        get {
            return this.nextCalibrationDateField;
        }
        set {
            this.nextCalibrationDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NextCalibrationDateSpecified {
        get {
            return this.nextCalibrationDateFieldSpecified;
        }
        set {
            this.nextCalibrationDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string CalibrationInitials {
        get {
            return this.calibrationInitialsField;
        }
        set {
            this.calibrationInitialsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(SensorConfigurationType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectDevices:1.3")]
public abstract partial class AbstractConfigurationType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectDevices:1.3")]
public partial class ComponentConfigurationType {
    
    private SensorConfigurationType itemField;
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SensorConfiguration")]
    public SensorConfigurationType Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectDevices:1.3")]
[System.Xml.Serialization.XmlRootAttribute("SensorConfiguration", Namespace="urn:mtconnect.org:MTConnectDevices:1.3", IsNullable=false)]
public partial class SensorConfigurationType : AbstractConfigurationType {
    
    private string firmwareVersionField;
    
    private System.DateTime calibrationDateField;
    
    private bool calibrationDateFieldSpecified;
    
    private System.DateTime nextCalibrationDateField;
    
    private bool nextCalibrationDateFieldSpecified;
    
    private string calibrationInitialsField;
    
    private ChannelType[] channelsField;
    
    /// <remarks/>
    public string FirmwareVersion {
        get {
            return this.firmwareVersionField;
        }
        set {
            this.firmwareVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime CalibrationDate {
        get {
            return this.calibrationDateField;
        }
        set {
            this.calibrationDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CalibrationDateSpecified {
        get {
            return this.calibrationDateFieldSpecified;
        }
        set {
            this.calibrationDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime NextCalibrationDate {
        get {
            return this.nextCalibrationDateField;
        }
        set {
            this.nextCalibrationDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NextCalibrationDateSpecified {
        get {
            return this.nextCalibrationDateFieldSpecified;
        }
        set {
            this.nextCalibrationDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string CalibrationInitials {
        get {
            return this.calibrationInitialsField;
        }
        set {
            this.calibrationInitialsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Channel", IsNullable=false)]
    public ChannelType[] Channels {
        get {
            return this.channelsField;
        }
        set {
            this.channelsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectDevices:1.3")]
public partial class ComponentDescriptionType {
    
    private System.Xml.XmlNode[] anyField;
    
    private string manufacturerField;
    
    private string modelField;
    
    private string serialNumberField;
    
    private string stationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlNode[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string manufacturer {
        get {
            return this.manufacturerField;
        }
        set {
            this.manufacturerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string model {
        get {
            return this.modelField;
        }
        set {
            this.modelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string serialNumber {
        get {
            return this.serialNumberField;
        }
        set {
            this.serialNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string station {
        get {
            return this.stationField;
        }
        set {
            this.stationField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DeviceType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CommonComponentType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(InterfaceType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ChuckInterfaceType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DoorInterfaceType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(MaterialHandlerType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BarFeederType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(InterfacesType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(SystemType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ElectricType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CoolantType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(LubricationType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(HydraulicType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PneumaticType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(SystemsType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AxisType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(SpindleType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(RotaryType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(LinearType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AxesType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DoorType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ActuatorType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PathType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(SensorType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PowerType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ControllerType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectDevices:1.3")]
public abstract partial class ComponentType {
    
    private ComponentDescriptionType descriptionField;
    
    private ComponentConfigurationType configurationField;
    
    private DataItemType[] dataItemsField;
    
    private ComponentType[] componentsField;
    
    private string idField;
    
    private string nativeNameField;
    
    private float sampleIntervalField;
    
    private bool sampleIntervalFieldSpecified;
    
    private float sampleRateField;
    
    private bool sampleRateFieldSpecified;
    
    /// <remarks/>
    public ComponentDescriptionType Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public ComponentConfigurationType Configuration {
        get {
            return this.configurationField;
        }
        set {
            this.configurationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("DataItem", IsNullable=false)]
    public DataItemType[] DataItems {
        get {
            return this.dataItemsField;
        }
        set {
            this.dataItemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Component", IsNullable=false)]
    public ComponentType[] Components {
        get {
            return this.componentsField;
        }
        set {
            this.componentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string nativeName {
        get {
            return this.nativeNameField;
        }
        set {
            this.nativeNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float sampleInterval {
        get {
            return this.sampleIntervalField;
        }
        set {
            this.sampleIntervalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool sampleIntervalSpecified {
        get {
            return this.sampleIntervalFieldSpecified;
        }
        set {
            this.sampleIntervalFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float sampleRate {
        get {
            return this.sampleRateField;
        }
        set {
            this.sampleRateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool sampleRateSpecified {
        get {
            return this.sampleRateFieldSpecified;
        }
        set {
            this.sampleRateFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectDevices:1.3")]
[System.Xml.Serialization.XmlRootAttribute("Device", Namespace="urn:mtconnect.org:MTConnectDevices:1.3", IsNullable=false)]
public partial class DeviceType : ComponentType {
    
    private string iso841ClassField;
    
    private string uuidField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string iso841Class {
        get {
            return this.iso841ClassField;
        }
        set {
            this.iso841ClassField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uuid {
        get {
            return this.uuidField;
        }
        set {
            this.uuidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(InterfaceType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ChuckInterfaceType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DoorInterfaceType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(MaterialHandlerType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BarFeederType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(InterfacesType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(SystemType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ElectricType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CoolantType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(LubricationType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(HydraulicType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PneumaticType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(SystemsType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AxisType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(SpindleType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(RotaryType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(LinearType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AxesType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DoorType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ActuatorType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PathType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(SensorType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PowerType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ControllerType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectDevices:1.3")]
[System.Xml.Serialization.XmlRootAttribute("CommonComponent", Namespace="urn:mtconnect.org:MTConnectDevices:1.3", IsNullable=false)]
public partial class CommonComponentType : ComponentType {
    
    private string uuidField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uuid {
        get {
            return this.uuidField;
        }
        set {
            this.uuidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ChuckInterfaceType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DoorInterfaceType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(MaterialHandlerType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BarFeederType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectDevices:1.3")]
public abstract partial class InterfaceType : CommonComponentType {
    
    private ReferenceType[] referencesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Reference", IsNullable=false)]
    public ReferenceType[] References {
        get {
            return this.referencesField;
        }
        set {
            this.referencesField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(SpindleType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(RotaryType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(LinearType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectDevices:1.3")]
public abstract partial class AxisType : CommonComponentType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectDevices:1.3")]
[System.Xml.Serialization.XmlRootAttribute("Controller", Namespace="urn:mtconnect.org:MTConnectDevices:1.3", IsNullable=false)]
public partial class ControllerType : CommonComponentType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectDevices:1.3")]
[System.Xml.Serialization.XmlRootAttribute("Power", Namespace="urn:mtconnect.org:MTConnectDevices:1.3", IsNullable=false)]
public partial class PowerType : CommonComponentType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectDevices:1.3")]
[System.Xml.Serialization.XmlRootAttribute("Sensor", Namespace="urn:mtconnect.org:MTConnectDevices:1.3", IsNullable=false)]
public partial class SensorType : CommonComponentType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectDevices:1.3")]
[System.Xml.Serialization.XmlRootAttribute("Path", Namespace="urn:mtconnect.org:MTConnectDevices:1.3", IsNullable=false)]
public partial class PathType : CommonComponentType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectDevices:1.3")]
[System.Xml.Serialization.XmlRootAttribute("Actuator", Namespace="urn:mtconnect.org:MTConnectDevices:1.3", IsNullable=false)]
public partial class ActuatorType : CommonComponentType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectDevices:1.3")]
[System.Xml.Serialization.XmlRootAttribute("Door", Namespace="urn:mtconnect.org:MTConnectDevices:1.3", IsNullable=false)]
public partial class DoorType : CommonComponentType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectDevices:1.3")]
[System.Xml.Serialization.XmlRootAttribute("Axes", Namespace="urn:mtconnect.org:MTConnectDevices:1.3", IsNullable=false)]
public partial class AxesType : CommonComponentType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectDevices:1.3")]
[System.Xml.Serialization.XmlRootAttribute("Linear", Namespace="urn:mtconnect.org:MTConnectDevices:1.3", IsNullable=false)]
public partial class LinearType : AxisType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectDevices:1.3")]
[System.Xml.Serialization.XmlRootAttribute("Rotary", Namespace="urn:mtconnect.org:MTConnectDevices:1.3", IsNullable=false)]
public partial class RotaryType : AxisType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectDevices:1.3")]
[System.Xml.Serialization.XmlRootAttribute("Spindle", Namespace="urn:mtconnect.org:MTConnectDevices:1.3", IsNullable=false)]
public partial class SpindleType : AxisType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectDevices:1.3")]
[System.Xml.Serialization.XmlRootAttribute("Systems", Namespace="urn:mtconnect.org:MTConnectDevices:1.3", IsNullable=false)]
public partial class SystemsType : CommonComponentType {
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ElectricType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CoolantType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(LubricationType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(HydraulicType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PneumaticType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectDevices:1.3")]
[System.Xml.Serialization.XmlRootAttribute("System", Namespace="urn:mtconnect.org:MTConnectDevices:1.3", IsNullable=false)]
public partial class SystemType : CommonComponentType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectDevices:1.3")]
[System.Xml.Serialization.XmlRootAttribute("Pneumatic", Namespace="urn:mtconnect.org:MTConnectDevices:1.3", IsNullable=false)]
public partial class PneumaticType : SystemType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectDevices:1.3")]
[System.Xml.Serialization.XmlRootAttribute("Hydraulic", Namespace="urn:mtconnect.org:MTConnectDevices:1.3", IsNullable=false)]
public partial class HydraulicType : SystemType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectDevices:1.3")]
[System.Xml.Serialization.XmlRootAttribute("Lubrication", Namespace="urn:mtconnect.org:MTConnectDevices:1.3", IsNullable=false)]
public partial class LubricationType : SystemType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectDevices:1.3")]
[System.Xml.Serialization.XmlRootAttribute("Coolant", Namespace="urn:mtconnect.org:MTConnectDevices:1.3", IsNullable=false)]
public partial class CoolantType : SystemType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectDevices:1.3")]
[System.Xml.Serialization.XmlRootAttribute("Electric", Namespace="urn:mtconnect.org:MTConnectDevices:1.3", IsNullable=false)]
public partial class ElectricType : SystemType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectDevices:1.3")]
[System.Xml.Serialization.XmlRootAttribute("Interfaces", Namespace="urn:mtconnect.org:MTConnectDevices:1.3", IsNullable=false)]
public partial class InterfacesType : CommonComponentType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectDevices:1.3")]
[System.Xml.Serialization.XmlRootAttribute("BarFeeder", Namespace="urn:mtconnect.org:MTConnectDevices:1.3", IsNullable=false)]
public partial class BarFeederType : InterfaceType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectDevices:1.3")]
[System.Xml.Serialization.XmlRootAttribute("MaterialHandler", Namespace="urn:mtconnect.org:MTConnectDevices:1.3", IsNullable=false)]
public partial class MaterialHandlerType : InterfaceType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectDevices:1.3")]
[System.Xml.Serialization.XmlRootAttribute("DoorInterface", Namespace="urn:mtconnect.org:MTConnectDevices:1.3", IsNullable=false)]
public partial class DoorInterfaceType : InterfaceType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mtconnect.org:MTConnectDevices:1.3")]
[System.Xml.Serialization.XmlRootAttribute("ChuckInterface", Namespace="urn:mtconnect.org:MTConnectDevices:1.3", IsNullable=false)]
public partial class ChuckInterfaceType : InterfaceType {
}
